### ISSUE TITLE
Other Currency Support and RabitMQ Plugin

### ISSUE THREAD

**Issue by princessfrombabylon99** [tomk1v/binance-pay-module#1]
1) Could you please add other currencies also?
2) I installed RabbitMQ, Do I have to enable any specific plugin of RabbitMQ?

**Comment by tomk1v** [comment]
Hello,1) For now it’s only USDT available, for other currencies(for example BTC, ETH, SOL) need to add converting logic. You can feel free to add this functionality.2) You need to install rabitmq and configure it in Magento configuration and also start queue in Magento root folder5 лист. 2024 р. о 18:45 SB ***@***.***> пише:﻿

Could you please add other currencies also?
I installed RabbitMQ, Do I have to enable any specific plugin of RabbitMQ?

**Comment by princessfrombabylon99** [comment]
> Hey,
> 
> 1. Additional currencies may be added in the future. Currently, there are some challenges with fetching real-time rates for more volatile coins like ETH or BTC. Since this module is open source, you're welcome to implement this logic and submit a pull request – I'd be happy to review it.
> 2. **No additional RabbitMQ plugins are needed**. Simply install RabbitMQ on your server, configure it with Magento, and start the Magento queue with the following command:
>    `bin/magento queue:consumers:start binance.order.creation &`

Thank you for your prompt reply. Last night, I saw your post on LinkedIn, I configured RabbitMQ. Tonight , I am gonna give it a try. I can't send PR as I am not a developer. I rely on community too. Meanwhile, I recommend , open discussions forum for this repository. Doing so will help us to request features and discuss general questions. You've done an awesome Job.

**Comment by tomk1v** [comment]
Thank you for your suggestion! I've opened this repository's discussion forum, so feel free to post any feature requests or general questions there. I'm glad to hear that you're trying out the RabbitMQ setup! Let me know if your queue runs successfully or you have any issues – I'd be happy to help. 😊
